		#### TABLE 생성 (CREATE TABLE)
-- 아이콘 테이블 (ICON TABLE)
CREATE TABLE ICON_TABLE (
    ICON_KEY VARCHAR(30) PRIMARY KEY COMMENT '아이콘 키 값',
    ICON VARCHAR(30) NOT NULL COMMENT '아이콘 이름',
    COLOR VARCHAR(12) DEFAULT '#A3A3A3' COMMENT '아이콘 색상 (기본값 : 짙은 회색)',
    VISIBLE INT COMMENT '유저 사용 여부 (0: 관리자용, 1: 유저용)'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 직업 카테고리 인덱스용 AUTO_INCREMENT 대체 시퀀스
CREATE TABLE JOB_CATEGORY (
    JOB_IDX BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '직업 인덱스',
    JOB_NAME VARCHAR(50) NOT NULL COMMENT '직업 이름',
    ICON_KEY VARCHAR(30) COMMENT '아이콘 키 FK(ICON_TABLE)',
    VISIBLE INT DEFAULT 1 COMMENT '조회 가능 여부 0:불가 1:가능',
    IS_DELETED BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_JOB_ICON FOREIGN KEY (ICON_KEY) REFERENCES ICON_TABLE(ICON_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 탑메뉴 카테고리
CREATE TABLE TOP_CATEGORY (
    TOP_IDX BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '탑메뉴 인덱스',
    PARENT_IDX BIGINT COMMENT '상위 카테고리 IDX (대분류: NULL)',
    TOP_NAME VARCHAR(100) NOT NULL COMMENT '탑메뉴 명',
    TOP_ADDR VARCHAR(100) COMMENT '탑메뉴 연결 API주소',
    CATEGORY_LEVEL INT DEFAULT 1 COMMENT '카테고리 수준 (1: 대분류, 2: 소분류 등)',
    ORD_COL INT COMMENT '탑메뉴 노출 순서',
    CONSTRAINT FK_TOP_PARENT FOREIGN KEY (PARENT_IDX) REFERENCES TOP_CATEGORY(TOP_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 목표 카테고리
CREATE TABLE TARGET_CATEGORY (
    TARGET_IDX BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '목표 인덱스',
    TARGET_NAME VARCHAR(100) NOT NULL COMMENT '목표 이름',
    ICON_KEY VARCHAR(30) COMMENT '아이콘 인덱스 FK(ICON_TABLE)',
    IS_DELETED BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_TARGET_ICON FOREIGN KEY (ICON_KEY) REFERENCES ICON_TABLE(ICON_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 챌린지 카테고리
CREATE TABLE CHALL_CATEGORY (
    CHALL_CATEGORY_IDX BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '챌린지 카테고리 인덱스',
    CHALL_NAME VARCHAR(100) NOT NULL COMMENT '챌린지 카테고리 이름',
    ICON_KEY VARCHAR(30) COMMENT '아이콘 인덱스 FK(ICON_TABLE)',
    IS_DELETED BOOLEAN DEFAULT FALSE COMMENT '삭제 여부',
    CONSTRAINT FK_CHALL_ICON FOREIGN KEY (ICON_KEY) REFERENCES ICON_TABLE(ICON_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 권한 카테고리
CREATE TABLE AUTHORITY_CATEGORY (
    AUTHORITY_IDX BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '권한 인덱스',
    AUTHORITY_NAME VARCHAR(100) NOT NULL COMMENT '권한 이름',
    AUTHORITY_DESCRIPTION VARCHAR(300) COMMENT '권한 설명'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- FAQ 카테고리
CREATE TABLE FAQ_CATEGORY (
    FAQ_CATEGORY_IDX BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'FAQ 카테고리 인덱스',
    FAQ_CATEGORY_NAME VARCHAR(100) NOT NULL COMMENT 'FAQ 카테고리 이름'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- QNA 카테고리
CREATE TABLE QNA_CATEGORY (
    CATEGORY_IDX BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '카테고리 고유 IDX',
    PARENT_IDX BIGINT COMMENT '상위 카테고리 IDX (대분류: NULL)',
    CATEGORY_NAME VARCHAR(100) NOT NULL COMMENT '카테고리 이름',
    CATEGORY_LEVEL INT DEFAULT 1 COMMENT '카테고리 수준 (1: 대분류, 2: 소분류 등)',
    CREATE_DATE DATE DEFAULT CURRENT_DATE COMMENT '생성일',
    UPDATE_DATE DATE DEFAULT CURRENT_DATE COMMENT '수정일',
    DEPRECATED INT DEFAULT 0 COMMENT '삭제 OR 사용 여부',
    CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENT_IDX) REFERENCES QNA_CATEGORY (CATEGORY_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 유저 테이블
CREATE TABLE USER_TABLE (
    USER_IDX BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '유저 인덱스',
    USER_NAME VARCHAR(50) NOT NULL COMMENT '유저 이름',
    USER_ID VARCHAR(50) NOT NULL UNIQUE COMMENT '유저 아이디',
    USER_PW VARCHAR(150) NOT NULL COMMENT '유저 비밀번호',
    USER_NICK VARCHAR(50) NOT NULL COMMENT '유저 닉네임',
    NICK_TAG VARCHAR(10) DEFAULT '#1' COMMENT '닉네임 중복 태그',
    USER_EMAIL VARCHAR(100) NOT NULL UNIQUE COMMENT '유저 이메일',
    JOB_IDX BIGINT DEFAULT 1 COMMENT '유저 직업 FK (JOB_CATEGORY)',
    TARGET_IDX BIGINT DEFAULT 1 COMMENT '유저 초기 목표 FK (TARGET_CATEGORY)',
    USER_PHONE VARCHAR(14) NOT NULL COMMENT '유저 전화번호',
    USER_GENDER INT DEFAULT 1 COMMENT '유저 성별 [1:남, 2:여, 3:중성]',
    USER_JOIN DATE DEFAULT CURRENT_DATE COMMENT '유저 가입일',
    AUTHORITY_IDX BIGINT DEFAULT 1 COMMENT '유저 권한(관리자 계정용)',
    COMBO INT DEFAULT 0 COMMENT '루틴 인증 콤보',
    USER_EXP INT DEFAULT 0 COMMENT '유저 경험치',
    IS_DELETED CHAR(1) DEFAULT 'N' COMMENT '계정 삭제 여부 [N:사용중, Y:삭제대기, D:삭제완료]',
    DELETE_DATE DATE COMMENT '삭제일',
    REPORT_COUNT INT COMMENT '신고 건수',
    IS_BANNED INT DEFAULT 0 COMMENT '접근 제한 여부',
    CONSTRAINT FK_USER_JOB FOREIGN KEY (JOB_IDX) REFERENCES JOB_CATEGORY(JOB_IDX),
    CONSTRAINT FK_USER_TARGET FOREIGN KEY (TARGET_IDX) REFERENCES TARGET_CATEGORY(TARGET_IDX),
    CONSTRAINT FK_USER_AUTHORITY FOREIGN KEY (AUTHORITY_IDX) REFERENCES AUTHORITY_CATEGORY(AUTHORITY_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 유저 레벨 테이블
CREATE TABLE USER_LEVEL (
    LV_IDX BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '레벨 인덱스',
    MIN_EXP INT NOT NULL COMMENT '최소 경험치',
    MAX_EXP INT NOT NULL COMMENT '최대 경험치'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 유저 신고 테이블
CREATE TABLE USER_REPORT (
    USER_REPORT_IDX BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '고유 신고 인덱스',
    REPORTER_IDX BIGINT NOT NULL COMMENT '신고자 인덱스 FK (USER_TABLE)',
    REPORTED_IDX BIGINT NOT NULL COMMENT '피신고자 인덱스 FK (USER_TABLE)',
    REPORT_REASON VARCHAR(2000) NOT NULL COMMENT '신고 사유',
    STATUS INT DEFAULT 0 COMMENT '신고 상태 (0:처리중 / 1:완료)',
    REPORT_DATE DATE DEFAULT CURRENT_DATE COMMENT '신고 접수일',
    
    CONSTRAINT UQ_USER_REPORT_UNIQUE UNIQUE (REPORTER_IDX, REPORTED_IDX),
    CONSTRAINT FK_USER_REPORTER FOREIGN KEY (REPORTER_IDX) REFERENCES USER_TABLE(USER_IDX),
    CONSTRAINT FK_USER_REPORTED FOREIGN KEY (REPORTED_IDX) REFERENCES USER_TABLE(USER_IDX),
    CONSTRAINT CK_SELF_REPORT CHECK (REPORTER_IDX <> REPORTED_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




-- FAQ 테이블
CREATE TABLE FAQ_TABLE (
    FAQ_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'FAQ 고유 인덱스',
    FAQ_TITLE VARCHAR(255) NOT NULL COMMENT 'FAQ 제목',
    FAQ_ANSWER TEXT COMMENT 'FAQ 답변',
    FAQ_CATEGORY BIGINT NOT NULL COMMENT '질문 카테고리',
    CONSTRAINT FK_FAQ_CATEGORY FOREIGN KEY (FAQ_CATEGORY) REFERENCES FAQ_CATEGORY (FAQ_CATEGORY_IDX)
);

CREATE INDEX FAQ_CATEGORY_IDX ON FAQ_TABLE(FAQ_CATEGORY);

CREATE FULLTEXT INDEX faq_title_idx ON FAQ_TABLE(FAQ_TITLE);
CREATE FULLTEXT INDEX faq_answer_idx ON FAQ_TABLE(FAQ_ANSWER);

-- QNA 테이블
CREATE TABLE QNA_TABLE (
    QNA_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '질문 고유 인덱스',
    Q_USER_IDX BIGINT NOT NULL COMMENT '질문자 인덱스 (유저)',
    TITLE VARCHAR(255) NOT NULL COMMENT '질문 제목',
    CONTENT TEXT NOT NULL COMMENT '질문 내용',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '질문 작성일',
    MODIFIED_AT DATETIME NULL COMMENT '질문 수정일',
    CATEGORY BIGINT NULL COMMENT '질문 카테고리',
    A_USER_IDX BIGINT NULL COMMENT '답변 담당자 인덱스 (관리자)',
    Q_COUNT INT DEFAULT 0 COMMENT '재질문 개수',
    A_COUNT INT DEFAULT 0 COMMENT '답변 개수',
    QNA_STATUS VARCHAR(15) NOT NULL COMMENT '문의 상태',
    RESPONDING_DATE DATETIME NULL COMMENT '응대 날짜',
    CONSTRAINT FK_Q_USER FOREIGN KEY (Q_USER_IDX) REFERENCES USER_TABLE(USER_IDX),
    CONSTRAINT FK_A_USER FOREIGN KEY (A_USER_IDX) REFERENCES USER_TABLE(USER_IDX),
    CONSTRAINT FK_QNA_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES QNA_CATEGORY (CATEGORY_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 답변 테이블
CREATE TABLE QNA_REPLY (
    QNA_REPLY_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '질문 컨텐츠 인덱스',
    QNA_IDX BIGINT NOT NULL COMMENT '질문 부모 인덱스 (QNA_IDX)',
    USER_IDX BIGINT NOT NULL COMMENT '응답자 인덱스',
    CONTENT TEXT NOT NULL COMMENT '응답 내용',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '문답 작성일',
    MODIFIED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '문답 수정일',
    CONSTRAINT FK_QNA_IDX FOREIGN KEY (QNA_IDX) REFERENCES QNA_TABLE(QNA_IDX),
    CONSTRAINT FK_QNA_USER FOREIGN KEY (USER_IDX) REFERENCES USER_TABLE(USER_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 공지사항 테이블
CREATE TABLE NOTICE_TABLE (
    NOTICE_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '공지 인덱스',
    NOTICE_TITLE VARCHAR(255) NOT NULL COMMENT '공지 제목',
    NOTICE_SUB TEXT NOT NULL COMMENT '공지 내용',
    USER_IDX BIGINT NOT NULL COMMENT '공지 작성자 인덱스 번호 FK (USER_TABLE) (관리자)',
    NOTICE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '공지 작성일',
    NOTICE_MODIFY DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '공지 수정일',
    IS_POPUP ENUM('Y', 'N') DEFAULT 'N' COMMENT '팝업 여부',
    POPUP_START_DATE DATETIME NULL COMMENT '팝업 게시일',
    POPUP_END_DATE DATETIME NULL COMMENT '팝업 게시 종료일',
    CONSTRAINT FK_NOTICE_USER FOREIGN KEY (USER_IDX) REFERENCES USER_TABLE(USER_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 루틴 테이블
CREATE TABLE PLAN_TABLE (
    PLAN_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '루틴 인덱스',
    USER_IDX BIGINT NOT NULL COMMENT '루틴 작성자 인덱스 번호 FK(USER_TABLE)',
    FORK_IDX BIGINT NULL COMMENT '원본 인덱스',
    PLAN_TITLE VARCHAR(255) NOT NULL COMMENT '루틴 제목',
    END_TO INT DEFAULT 7 COMMENT '루틴 목표 개월 수 [최소 기간 1주]',
    TARGET_IDX BIGINT DEFAULT 1 COMMENT '목표 카테고리 인덱스 번호 FK(TARGET_CATEGORY)',
    JOB_IDX BIGINT DEFAULT 1 COMMENT '직업 카테고리 인덱스 번호 FK(JOB_CATEGORY)',
    PLAN_IMP INT DEFAULT 1 COMMENT '루틴 중요도',
    REPEAT_DAYS VARCHAR(50) NULL COMMENT '반복 요일',

    PLAN_SUB_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '루틴 작성일',
    PLAN_SUB_MOD DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '루틴 수정일',
    PLAN_SUB_START DATETIME NULL COMMENT '루틴 시작일',
    PLAN_SUB_END DATETIME NULL COMMENT '루틴 종료일',

    VIEW_COUNT INT DEFAULT 0 COMMENT '조회 수',
    FORK_COUNT INT DEFAULT 0 COMMENT '포크 수 (따라하기)',
    CERT_EXP INT DEFAULT 0 COMMENT '인증 경험치',
    LAST_EXP INT DEFAULT 0 COMMENT '마지막 인증 시점 경험치',
    LIKE_COUNT INT DEFAULT 0 COMMENT '추천 수',
    IS_SHARED TINYINT(1) DEFAULT 0 COMMENT '공개 여부 [0: 비공개, 1: 공유]',
    IS_ACTIVE TINYINT(1) DEFAULT 0 COMMENT '활성 여부 [0: 비활성, 1: 활성]',
    IS_COMPLETED TINYINT(1) DEFAULT 0 COMMENT '종료 여부 [0: 진행 중, 1: 완료]',
    IS_DELETED TINYINT(1) DEFAULT 0 COMMENT '삭제 여부 [0: 삭제안함 1: 삭제함]',
    FIRE_STATE TINYINT(1) DEFAULT 0 COMMENT '불꽃 활성화 여부 [0: 비활성 1: 활성]',

    REVIEW VARCHAR(500) NULL COMMENT '루틴 완료 후기',

    CONSTRAINT FK_PLAN_USER FOREIGN KEY (USER_IDX) REFERENCES USER_TABLE(USER_IDX),
    CONSTRAINT FK_PLAN_TARGET FOREIGN KEY (TARGET_IDX) REFERENCES TARGET_CATEGORY(TARGET_IDX),
    CONSTRAINT FK_PLAN_JOB FOREIGN KEY (JOB_IDX) REFERENCES JOB_CATEGORY(JOB_IDX),
    CONSTRAINT FK_PLAN_FORK FOREIGN KEY (FORK_IDX) REFERENCES PLAN_TABLE(PLAN_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 좋아요 테이블
CREATE TABLE LIKE_TABLE (
    USER_IDX BIGINT COMMENT '사용자 IDX FK(USER_TABLE)',
    PLAN_IDX BIGINT COMMENT '게시글 IDX FK(PLAN_TABLE)',
    LIKE_TIMESTAMP DATETIME COMMENT '추천(좋아요)한 시간',
    PRIMARY KEY (USER_IDX, PLAN_IDX),
    CONSTRAINT FK_LIKE_USER_IDX FOREIGN KEY (USER_IDX) REFERENCES USER_TABLE(USER_IDX),
    CONSTRAINT FK_LIKE_PLAN_IDX FOREIGN KEY (PLAN_IDX) REFERENCES PLAN_TABLE(PLAN_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 루틴 신고 테이블
CREATE TABLE PLAN_REPORT (
	PLAN_REPORT_IDX BIGINT AUTO_INCREMENT COMMENT '루틴 신고 고유 인덱스',
    REPORTER_IDX BIGINT NOT NULL COMMENT '신고자 인덱스 FK (USER_TABLE)',
    PLAN_IDX BIGINT NOT NULL COMMENT '루틴 인덱스 FK (PLAN_TABLE)',
    REPORT_REASON VARCHAR(2000) NOT NULL COMMENT '신고 사유',
    STATUS INT DEFAULT 0 COMMENT '신고 상태 (0:처리중 / 1:완료)',
    REPORT_DATE DATE DEFAULT CURRENT_DATE COMMENT '신고 접수일',

    PRIMARY KEY (REPORTER_IDX, PLAN_IDX),
    CONSTRAINT FK_PLAN_REPORTER FOREIGN KEY (REPORTER_IDX) REFERENCES USER_TABLE(USER_IDX),
    CONSTRAINT FK_PLAN_REPORTED FOREIGN KEY (PLAN_IDX) REFERENCES PLAN_TABLE(PLAN_IDX),
    CONSTRAINT UQ_PLAN_REPORT_IDX UNIQUE (PLAN_REPORT_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 활동 테이블
CREATE TABLE PLAN_ACTIVITY (
    ACTIVITY_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '활동 고유 인덱스',
    PLAN_IDX BIGINT NOT NULL COMMENT '루틴 인덱스 FK(PLAN_TABLE)',
    ACTIVITY_NAME VARCHAR(100) NOT NULL COMMENT '활동명',
    SET_TIME DATETIME NULL COMMENT '시간 지정',
    DESCRIPTION VARCHAR(500) NULL COMMENT '구체적인 설명',
    ACTIVITY_IMP INT DEFAULT 1 COMMENT '활동 중요도',
    IS_DELETED TINYINT(1) DEFAULT 0 COMMENT '삭제 여부',

    CONSTRAINT FK_ROUTAIN_PLAN FOREIGN KEY (PLAN_IDX) REFERENCES PLAN_TABLE(PLAN_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 챌린지 테이블
CREATE TABLE CHALL_TABLE (
    CHALL_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '챌린지 인덱스',
    CHALL_TITLE VARCHAR(255) NOT NULL COMMENT '챌린지 제목',
    CHALL_DESCRIPTION TEXT NOT NULL COMMENT '챌린지 설명',
    CHALL_CATEGORY_IDX BIGINT NOT NULL COMMENT '챌린지 카테고리 FK(CHALL_CATEGORY)',
    MIN_PARTICIPATION_TIME INT DEFAULT 0 COMMENT '최소 참여 시간 설정',
    TOTAL_CLEAR_TIME INT DEFAULT 0 COMMENT '총 클리어 시간 (HP)',
    MAX_PARTICIPANTS INT DEFAULT 0 COMMENT '참여 인원 제한',
    CHALL_CREATED_AT DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '챌린지 등록일',
    CHALL_START_TIME DATETIME NULL COMMENT '시작 시간 (NULL 가능)',
    CHALL_END_TIME DATETIME NULL COMMENT '종료 시간 (NULL 가능)',
    CHALL_STATE VARCHAR(20) DEFAULT 'PUBLISHED' COMMENT '챌린지 상태 (종료, 게시중, 진행중)',
    USER_JOIN TINYINT(1) DEFAULT 0 COMMENT '유저 참여형 챌린지 여부',
    DURATION INT NULL COMMENT '유지기간',
    CONSTRAINT FK_CHALL_CATEGORY FOREIGN KEY (CHALL_CATEGORY_IDX) REFERENCES CHALL_CATEGORY(CHALL_CATEGORY_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 챌린지 참여 유저 테이블
CREATE TABLE CHALL_JOIN (
    CHALL_JOIN_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '챌린지 참여 유저 인덱스',
    CHALL_IDX BIGINT NOT NULL COMMENT '참여 챌린지 인덱스 번호 FK(CHALL_TABLE)',
    USER_IDX BIGINT NOT NULL COMMENT '참여한 유저 인덱스 번호 FK(USER_TABLE)',
    ACTIVITY VARCHAR(50) NOT NULL COMMENT '활동명',
    ACTIVITY_TIME INT DEFAULT 0 COMMENT '활동 시간',
    JOIN_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '참여일',

    CONSTRAINT FK_CHALL_JOIN_CHALL_IDX FOREIGN KEY (CHALL_IDX) REFERENCES CHALL_TABLE(CHALL_IDX),
    CONSTRAINT FK_CHALL_JOIN_USER_IDX FOREIGN KEY (USER_IDX) REFERENCES USER_TABLE(USER_IDX),

    CONSTRAINT UNQ_CHALL_JOIN UNIQUE (CHALL_IDX, USER_IDX) -- 같은 챌린지에 중복 참여 불가
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 인증 테이블
CREATE TABLE VERIFY_TABLE (
    VERIFY_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '인증 인덱스',
    ACTIVITY_IDX BIGINT NULL COMMENT '인증할 활동 인덱스 FK(PLAN_ACTIVITY)',
    CHALL_IDX BIGINT NULL COMMENT '인증할 챌린지 인덱스 FK(CHALL_TABLE)',
    USER_IDX BIGINT NOT NULL COMMENT '인증한 유저 인덱스 FK(USER_TABLE)',
    VERIFY_DATE DATE DEFAULT CURRENT_DATE COMMENT '인증 날짜',
    ELAPSED_TIME INT NULL COMMENT '경과 시간 (챌린지용)',
    START_TIME DATE NULL COMMENT '챌린지 활동 시작일',
    END_TIME DATE NULL COMMENT '챌린지 활동 종료일',

    CONSTRAINT FK_VERIFY_PLAN FOREIGN KEY (ACTIVITY_IDX) REFERENCES PLAN_ACTIVITY(ACTIVITY_IDX),
    CONSTRAINT FK_VERIFY_CHALL FOREIGN KEY (CHALL_IDX) REFERENCES CHALL_TABLE(CHALL_IDX),
    CONSTRAINT FK_VERIFY_USER FOREIGN KEY (USER_IDX) REFERENCES USER_TABLE(USER_IDX)

    -- CHECK 제약조건 (ACTIVITY_IDX IS NOT NULL OR CHALL_IDX IS NOT NULL) 
    -- MariaDB에서는 CHECK 제약조건을 완벽히 지원하지 않아 생략했습니다. 
    -- 해당 조건은 애플리케이션 레벨에서 반드시 검증해 주세요.
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 등급 테이블
CREATE TABLE FIRE_TABLE (
    LV_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '등급 인덱스 (레벨)',
    MIN_EXP INT NOT NULL COMMENT '최소 인증 경험치',
    MAX_EXP INT NOT NULL COMMENT '최대 인증 경험치',
    FIRE_NAME VARCHAR(100) NOT NULL COMMENT '불꽃 이름',
    FIRE_COLOR VARCHAR(50) NULL COMMENT '불꽃 색상',
    FIRE_EFFECT VARCHAR(255) NULL COMMENT '불꽃 이펙트'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 재발급 토큰 관리 테이블
CREATE TABLE REFRESH_TOKEN (
    TOKEN_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '고유 인덱스',
    USERNAME VARCHAR(50) NOT NULL COMMENT 'userId를 나타냄',
    REFRESH VARCHAR(200) NOT NULL COMMENT '발급된 리프레쉬 토큰',
    EXPIRATION DATETIME NOT NULL COMMENT '만료기한'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 기타 직업 카테고리 테이블
CREATE TABLE JOB_ETC_CATEGORY (
    JOB_ETC_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '기타 직업 인덱스',
    PLAN_IDX BIGINT NOT NULL COMMENT '루틴 인덱스 FK: PLAN_IDX',
    JOB_NAME VARCHAR(50) NOT NULL COMMENT '기타 직업 이름',
    ICON_KEY VARCHAR(30) NULL COMMENT '아이콘 키 FK(ICON_TABLE)',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '기타 직업 생성일',
    
    CONSTRAINT FK_ETC_JOB_ICON FOREIGN KEY (ICON_KEY) REFERENCES ICON_TABLE(ICON_KEY) ON DELETE CASCADE,
    CONSTRAINT FK_ETC_JOB_PLAN FOREIGN KEY (PLAN_IDX) REFERENCES PLAN_TABLE(PLAN_IDX) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 검색 기록 테이블
CREATE TABLE SEARCH_LOG (
    LOG_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '검색 기록 인덱스',
    UNIQUE_ID VARCHAR(36) NULL COMMENT '비로그인 유저 고유 ID',
    USER_IDX BIGINT NULL COMMENT '로그인 유저 고유 IDX',
    SEARCH_KEYWORD VARCHAR(120) NOT NULL COMMENT '검색어',
    SEARCH_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '검색 시간',
    SEARCH_COUNT INT DEFAULT 1 COMMENT '검색 횟수',
    IS_DELETED TINYINT(1) DEFAULT 0 COMMENT '삭제 여부',

    CONSTRAINT FK_LOG_USER_IDX FOREIGN KEY (USER_IDX) REFERENCES USER_TABLE(USER_IDX) ON DELETE CASCADE

    -- CHECK 제약조건 (UNIQUE_ID IS NOT NULL OR USER_IDX IS NOT NULL)
    -- MariaDB에서 완전 지원하지 않아 생략했습니다.
    -- 해당 조건은 애플리케이션 레벨에서 검증해 주세요.
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 고객센터 테이블
CREATE TABLE SERVICE_CENTER (
    USER_IDX BIGINT PRIMARY KEY COMMENT '고객센터 직원 인덱스 (FK : USER_TABLE(USER_IDX))',
    STATUS TINYINT(1) DEFAULT 0 COMMENT '상태값 (0: 비활성 / 1: 활성)',
    MATCHED INT DEFAULT 0 COMMENT '매칭된 문의 수',

    CONSTRAINT FK_SERVICE_USER FOREIGN KEY (USER_IDX) REFERENCES USER_TABLE(USER_IDX) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- QNA 일일 통계 테이블
CREATE TABLE QNA_DAILY_STATS (
    STAT_DATE DATE DEFAULT CURRENT_DATE COMMENT '통계 데이터 저장 일자',
    ADMIN_IDX BIGINT NOT NULL COMMENT '관리자(상담원) 인덱스',
    TOTAL_COUNT INT DEFAULT 0 COMMENT '일일 총 문의 처리량',
    TOTAL_DURATION INT DEFAULT 0 COMMENT '일일 총 처리 소요 시간 [초]',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '통계 데이터 생성 로그',
    PRIMARY KEY (STAT_DATE, ADMIN_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- QNA 월간 통계 테이블
CREATE TABLE QNA_MONTH_STATS (
    STAT_MONTH VARCHAR(7) NOT NULL COMMENT '통계 데이터 저장 일자 (YYYY-MM)',
    ADMIN_IDX BIGINT NOT NULL COMMENT '관리자(상담원) 인덱스',
    TOTAL_COUNT INT DEFAULT 0 COMMENT '월별 누적 처리량',
    TOTAL_DURATION INT DEFAULT 0 COMMENT '월별 누적 소요 시간 [초]',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '통계 데이터 생성 로그',
    PRIMARY KEY (STAT_MONTH, ADMIN_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 상담원 누적 통계 테이블
CREATE TABLE QNA_ADMIN_SUMMARY_STATS (
    ADMIN_IDX BIGINT PRIMARY KEY COMMENT '상담원 IDX',
    TOTAL_COUNT INT DEFAULT 0 COMMENT '전체 누적 처리 건수',
    TOTAL_DURATION INT DEFAULT 0 COMMENT '전체 누적 소요 시간',
    WORKING_DAYS INT DEFAULT 0 COMMENT '실제 근무 일수',
    AVG_QNA_PER_DAY INT DEFAULT 0 COMMENT '하루 평균 처리량',
    AVG_DURATION_PER_DAY INT DEFAULT 0 COMMENT '하루 평균 소요 시간',
    AVG_QNA_PER_MONTH INT DEFAULT 0 COMMENT '월 평균 처리량',
    AVG_DURATION_PER_MONTH INT DEFAULT 0 COMMENT '월 평균 소요 시간',
    RECENT_DURATION INT DEFAULT 0 COMMENT '최근 처리한 문의 소요 시간'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 관리자 채팅방 테이블
CREATE TABLE ADMIN_CHAT_ROOMS (
    ROOM_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '채팅방 고유 IDX',
    NAME VARCHAR(100) NOT NULL COMMENT '채팅방 이름',
    IS_PUBLIC TINYINT(1) DEFAULT 0 COMMENT '공개방 여부',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    CREATED_BY BIGINT NULL COMMENT '생성자 고유 IDX',
    IS_DELETED CHAR(1) DEFAULT 'N' COMMENT '채팅방 삭제 여부 (N : 삭제X / Y : 삭제 O)',
    DELETED_AT DATETIME NULL COMMENT '채팅방 삭제 일자',

    CONSTRAINT FK_ADMIN_CHAT_CREATOR FOREIGN KEY (CREATED_BY) REFERENCES USER_TABLE(USER_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 관리자 채팅방 참여자 테이블
CREATE TABLE ADMIN_CHAT_ROOM_ROLES (
    ROOM_IDX BIGINT NOT NULL COMMENT '채팅방 IDX',
    ROLE_IDX BIGINT NOT NULL COMMENT '접근 가능 권한 IDX',

    CONSTRAINT FK_ADMIN_CHAT_ROLES_ROOM_IDX FOREIGN KEY (ROOM_IDX) REFERENCES ADMIN_CHAT_ROOMS(ROOM_IDX) ON DELETE CASCADE,
    CONSTRAINT FK_ADMIN_CHAT_ROLES_AUTHORITY_IDX FOREIGN KEY (ROLE_IDX) REFERENCES AUTHORITY_CATEGORY(AUTHORITY_IDX) ON DELETE CASCADE,

    CONSTRAINT UNQ_ADMIN_CHAT_ROLES UNIQUE (ROOM_IDX, ROLE_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 관리자 채팅방 메시지 테이블
CREATE TABLE ADMIN_CHAT_ROOM_MESSAGES (
    CHAT_IDX BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '메시지 고유 인덱스 번호',
    ROOM_IDX BIGINT NOT NULL COMMENT '채팅방 고유 인덱스 번호',
    SENDER_IDX BIGINT NULL COMMENT '작성자 고유 인덱스 번호',
    MESSAGE_TYPE VARCHAR(20) DEFAULT 'TEXT' COMMENT 'TEXT / SYSTEM / IMAGE / FILE 등',
    CONTENT TEXT NOT NULL COMMENT '메시지 내용',
    FILE_PATH VARCHAR(255) NULL COMMENT '파일 저장 경로 (첨부파일)',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',

    CONSTRAINT FK_ADMIN_CHAT_MESSAGES_ROOM_IDX FOREIGN KEY (ROOM_IDX) REFERENCES ADMIN_CHAT_ROOMS(ROOM_IDX),
    CONSTRAINT FK_ADMIN_CHAT_MESSAGES_SENDER_IDX FOREIGN KEY (SENDER_IDX) REFERENCES USER_TABLE(USER_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 메시지 읽음 처리 테이블
CREATE TABLE ADMIN_CHAT_MESSAGE_READ (
    CHAT_IDX BIGINT NOT NULL COMMENT '메시지 고유 인덱스 번호',
    ADMIN_IDX BIGINT NOT NULL COMMENT '관리자 고유 인덱스 번호',
    READ_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '읽은 시간',
    PRIMARY KEY (CHAT_IDX, ADMIN_IDX),
    FOREIGN KEY (CHAT_IDX) REFERENCES ADMIN_CHAT_ROOM_MESSAGES(CHAT_IDX),
    FOREIGN KEY (ADMIN_IDX) REFERENCES USER_TABLE(USER_IDX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;