services:
  db:
    image: mariadb:11.8.2
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: god_life_db
      MYSQL_USER: godlife
      MYSQL_PASSWORD: godlife_2501
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.0.15
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/god_life_db
      SPRING_DATASOURCE_USERNAME: godlife
      SPRING_DATASOURCE_PASSWORD: godlife_2501
      SPRING_REDIS_HOST: redis
    networks:
      - godlife_net

volumes:
  db_data:
  redis_data:

networks:
  godlife_net:
