services:
  db:
    image: mariadb:11.8.2
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: god_life_db
      MYSQL_USER: godlife
      MYSQL_PASSWORD: godlife_2501
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - godlife-network

  redis:
    image: redis:7.0.15
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - godlife-network

  backend:
    image: godlife-backend:latest
    container_name: spring-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - redis
      - db
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - godlife-network

networks:
  godlife-network:
    driver: bridge

volumes:
  db_data:
  redis_data: